OnlineEducation.UI/Areas/Admin/Controllers/BannerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineEducation.UI.DTOs.BannerDtos;
using OnlineEducation.UI.Helpers;
using System.Threading.Tasks;

namespace OnlineEducation.UI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class BannerController : Controller
    {
        private readonly HttpClient _client;

        public BannerController(IHttpClientFactory clientFactory)
        {
            _client = clientFactory.CreateClient("RensEduClient");
        }
        public async Task<IActionResult> Index()
        {
            var values = await _client.GetFromJsonAsync <List<ResultBannerDto>>("banners");
            return View(values);
        }

        public IActionResult CreateBanner()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateBanner(CreateBannerDto createBannerDto)
        {
            await _client.PostAsJsonAsync("banners", createBannerDto);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> UpdateBanner(int id)
        {
            var value = await _client.GetFromJsonAsync<UpdateBannerDto>($"banners/{id}");
            return View(value);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateBanner(UpdateBannerDto updateBannerDto)
        {
            await _client.PutAsJsonAsync("banners", updateBannerDto);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> DeleteBanner(int id)
        {
            await _client.DeleteAsync($"banners/{id}");
            return RedirectToAction(nameof(Index));
        }


    }
}

OnlineEducation.UI/Areas/Admin/Views/Banner/CreateBanner.cshtml
@model CreateBannerDto
@{
    ViewData["Title"] = "Create Banner";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">
	
	<label>Title</label>
	<input type="text" asp-for="Title" class="form-control" />
	<br />
	<label>Image Url </label>
	<input type="text" asp-for="ImageUrl" class="form-control" />
	
	<button class="btn btn-outline-primary">Save</button>
</form>

OnlineEducation.UI/Areas/Admin/Views/Banner/Index.cshtml
@model List<ResultBannerDto>
@{
    ViewData["Title"] = "Banner Page";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}




@{
	int count = 0;
}

<table class="table table-hover">
	<tr>
		<th>#</th>
		<th>Title</th>
		<th></th>
	</tr>
	@foreach (var item in Model)
	{
		count++;
		<tr>
			<th>@count</th>
			<td>
				<img src="@item.ImageUrl" style="height: 75px; width: 75px;" /> @item.Title
			</td>
			
			<td>
				<a asp-action="DeleteBanner" onclick="deleteBanner(@item.BannerId)" asp-controller="Banner" asp-area="Admin" asp-route-id="@item.BannerId" class="btn btn-outline-danger">
					Remove
				</a>
				<a asp-action="UpdateBanner" asp-controller="Banner" asp-area="Admin" asp-route-id="@item.BannerId" class="btn btn-outline-info">
					Update
				</a>

			</td>
		</tr>

	}


</table>
<br />

<a asp-action="CreateBanner" asp-controller="Banner" asp-area="Admin" class="btn btn-outline-primary float-end"> Create Banner</a>

<script>

	function deleteBanner(id){


		Swal.fire({
	  title: "Are you sure?",
	  text: "You won't be able to revert this!",
	  icon: "warning",
	  showCancelButton: true,
	  confirmButtonColor: "#3085d6",
	  cancelButtonColor: "#d33",
	  confirmButtonText: "Yes, delete it!"
	}).then((result) => {
	  if (result.isConfirmed) {
		window.location.href = "/Admin/Banner/DeleteBanner/" + id;
	  }
	});
	}
</script>

OnlineEducation.UI/Areas/Admin/Views/Banner/UpdateBanner.cshtml
@model UpdateBannerDto
@{
    ViewData["Title"] = "Update Banner";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<form method="post">
	<input type="hidden" asp-for="BannerId"/>
	<label>Title</label>
	<input type="text" asp-for="Title" class="form-control" />
	<br />
	<label>Image Url </label>
	<input type="text" asp-for="ImageUrl" class="form-control" />

	<button class="btn btn-outline-primary">Update</button>
</form>